version: "3.8"
services:
  matcher_app:
    container_name: matcher_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    tty: true
    volumes:
      - .:/var/www
      - ./public:/var/www/public
    depends_on:
      - matcher_db
      - matcher_db_unit
    networks:
      - app_network

  matcher_db:
    container_name: matcher_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: matcher.test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  matcher_db_unit:
    container_name: matcher_db_unit
    image: mysql:8.0.20
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: matcher.unit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
