version: "3.8"
services:
  matcher_app:
    container_name: matcher_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - matcher_db
    networks:
      - app_network

  matcher_nginx:
    container_name: matcher_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - matcher_app
    environment:
      NGINX_FPM_HOST: matcher_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  matcher_db:
    container_name: matcher_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: matcher.test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
